#!/bin/bash


shrink() {
  if [[  $1 == *'shrinked'* ]]; then
    return 0
  fi

  filename=$(basename $1)
  filename=$(sed 's/\.pdf//g' $filename)

  shrink "$1" "${filename}_shrinked.pdf"

  if [ $? -ne 0 ]; then
    return 0
  fi

  rm "$1"
}

export -f shrink

find /pdf -iname '*.pdf' -type f -exec bash -c 'shrink "$0"' {} \;
