#!/bin/bash


do_shrink() {
  if [[  $1 == *'shrinked'* ]]; then
    return 0
  fi

  # remove .pdf ending from string
  filename=$(basename "$1")
  filename=$(echo $filename|sed 's/\.pdf//g')
  out=$OUTPUT_DIR
  if [ -z ${out+x} ]; then
    out=$(dirname "$1")
  fi

  echo "Shrinking $1 "
  shrink "$1" "${out}/${filename}_shrinked.pdf"

  if [ $? -ne 0 ]; then
    echo "erri while shrinking $1"
    return 0
  fi

  rm "$1"
}

export -f do_shrink

while [ true ]; do
  sleep 5
  find /pdf -iname '*.pdf' -type f -exec bash -c 'do_shrink "$0"' {} \;
done
